### ISSUE TITLE
Wrong merge of config

### ISSUE THREAD

**Issue by alesut** [onetwotrip/SimpleConfig#10]
If we have some part of config in YML file and another part in ENV variables - they wouldn't merge correctly.
Example of YML:
```
jira:
  auth_type: :basic
  context_path: ''
  tags:
    field: 'customfield_11001'
```
Example of ENV:
```
  username: <%= ENV['JIRA_USERNAME'] %>
  password: <%= ENV['JIRA_PASSWORD'] %>
  site:     <%= ENV['JIRA_SITE'] %>
  issue:    <%= ENV['ISSUE'] %>
```
Result:
```
  username: "SOME_USERNAME"
  password: "SOME_USERNAME"
  site:     "SOME_SITE"
  issue:   "SOME_ISSUE"
```
